FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim

ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENV APP_HOME=/app
RUN mkdir $APP_HOME -p
WORKDIR $APP_HOME

COPY ./bin/Release/netcoreapp2.2/publish $APP_HOME

ENTRYPOINT ["dotnet", "GamingWebApp.dll"]